"""empty message

Revision ID: d1d73c79340a
Revises: 
Create Date: 2023-07-25 08:08:33.862302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d73c79340a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adventurers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('distance', sa.String(), nullable=True),
    sa.Column('altitude', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_trails_location_id_locations')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hiked_trails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('adventurer_id', sa.Integer(), nullable=True),
    sa.Column('trail_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['adventurer_id'], ['adventurers.id'], name=op.f('fk_hiked_trails_adventurer_id_adventurers')),
    sa.ForeignKeyConstraint(['trail_id'], ['trails.id'], name=op.f('fk_hiked_trails_trail_id_trails')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trail_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(), nullable=True),
    sa.Column('adventurer_id', sa.Integer(), nullable=False),
    sa.Column('trail_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['adventurer_id'], ['adventurers.id'], name=op.f('fk_trail_reviews_adventurer_id_adventurers')),
    sa.ForeignKeyConstraint(['trail_id'], ['trails.id'], name=op.f('fk_trail_reviews_trail_id_trails')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trail_reviews')
    op.drop_table('hiked_trails')
    op.drop_table('trails')
    op.drop_table('locations')
    op.drop_table('adventurers')
    # ### end Alembic commands ###
